### ISSUE TITLE
Numbers with zeroed out fractional parts formatted wrong

### ISSUE THREAD

**Issue by jlauemoeller** [elixir-cldr/cldr_numbers#15]
There seems to be a problem with how numbers with zeroed out fractions are handled, cf:

```elixir 
Cldr.Number.to_string! 100000.01, fractional_digits: 2, locale: "en"
"100,000.01"

Cldr.Number.to_string! 100000.02, fractional_digits: 2, locale: "en"
"100,000.02"

Cldr.Number.to_string! 100000.00, fractional_digits: 2, locale: "en"
"99,999.99999999999"
```

This seems independent of the locale:

```elixir
Cldr.Number.to_string! 100000.00, fractional_digits: 2, locale: "da"
"99.999,99999999999"
```

**Comment by kipcole9** [comment]
Thanks for the report. You have identified a bug in my floating point rounding code. The reason I have my own code is because it implements the same rounding modes as the `Decimal` library only for floats - that way all natural numbers can implement the same rounding modes.

For a workaround for now, using a `Decimal` will work. I will work on a resolution over the next 24 hours. Apologies for the inconvenience.

The workaround:
```elixir
iex> Cldr.Number.to_string! Decimal.from_float(100000.00), fractional_digits: 2
"100,000.00"
```

**Comment by kipcole9** [comment]
The issued turned out to be a bit different but thankfully was a straight forward fix. Please update `cldr_utils` to version `2.15.1`:

```elixir
mix deps.update cldr_utils
mix compile
```
And I believe you should be good to go.  I will keep the issue open in case for some reason you do not see a correct result.

**Comment by jlauemoeller** [comment]
Thank you very much @kipcole9 fixing this so quickly -- much appreciated! 🙌

**Comment by kipcole9** [comment]
Glad its working for you. Will close the issue but please open again if for some reason its not fully resolved for you.
