### ISSUE TITLE
Feature request: Respect default backend more broadly?

### ISSUE THREAD

**Issue by petrus-jvrensburg** [elixir-cldr/cldr_numbers#41]
There are certain functions where a backend needs to be specified, even when a "default" backend has been configured. E.g.

```
Cldr.Number.System.number_system_from_locale(:hi, MyApp.Backend)
```

**Comment by petrus-jvrensburg** [comment]
`Cldr.Number.Format.format_styles_for("en", :latn, DemoApp.Backend)` is another example where the backend is not optional.

**Comment by kipcole9** [comment]
I will most definitely fix this - thanks for pointing it out and please keep doing so.  If I ever do a "Cldr version 3" I would do this differently. But since that's not likely to happen any time soon I do want to make sure that argument handling is consistent.

If you're ok I'll align with with [CLDR 44](https://cldr.unicode.org/index/downloads/cldr-44) which will likely ship in October.  If you need it in time for ElixirConf then I can at least get it fixed in time for that on the main branch.

**Comment by petrus-jvrensburg** [comment]
That timing sounds fine, no rush. Thanks. 

It's not broken... just good to keep chipping away at some of these things that a new dev could easily trip over.

**Comment by kipcole9** [comment]
> Cldr.Number.System.number_system_from_locale(:hi, MyApp.Backend)

Actually omitting the backend is already supported:
```elixir
iex> Cldr.Number.System.number_system_from_locale(:en)
:latn
```

> Cldr.Number.Format.format_styles_for("en", :latn, DemoApp.Backend)

This one doesn't default the backend so I'll work on that now.

**Comment by kipcole9** [comment]
> Cldr.Number.Format.format_styles_for("en", :latn)

Now also fixed.  All functions in the `Cldr.Number.Format` module will default the backend argument. I will gradually do the same for all the other modules.

```elixir
iex> Cldr.Number.Format.format_styles_for("en", :latn)
{:ok,
 [:scientific, :currency, :percent, :decimal_long, :decimal_short,
  :currency_short, :currency_long, :standard, :accounting,
  :accounting_alpha_next_to_number, :accounting_no_symbol,
  :currency_alpha_next_to_number, :currency_no_symbol]}
```

**Comment by kipcole9** [comment]
Closing for now since these specific functions now respect the default backend.  I will publish a new version now to be ready for your Elixir Confg talk.
